apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "ais.name" . }}-cr
rules:
  - apiGroups: [""]
    resources:
      # Required to retrieve the node label for the funky behavior of AIS
      # that it needs a special treatment to have a primary proxy to start.
      - "nodes"
      # Required to retrieve logs from the pods by ETL.
      - "pods/log"
    verbs: ["*"]  # XXX TODO - this is too liberal!
