apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "ais.name" . }}-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "ais.name" . }}-r
subjects:
- kind: ServiceAccount
  name: {{ template "ais.name" . }}-sa
