{{ if and ( and .Values.tags.builtin_monitoring .Values.grafana.persistence.enabled ) .Values.grafana.ais.pv.path }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ais-grafana-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ required "grafana PV capacity required" .Values.grafana.ais.pv.capacity | quote }}
  storageClassName: local-storage
  selector:
    matchLabels:
      consumer: grafana
{{ end }}