{{ if and ( and .Values.tags.builtin_monitoring .Values.graphite.persistence.enabled ) .Values.graphite.ais.pv.path }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ais-graphite-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ required "graphite PV capacity required" .Values.graphite.ais.pv.capacity | quote }}
  storageClassName: local-storage
  selector:
    matchLabels:
      consumer: graphite
{{ end }}
