---
{{ if and .Values.aiscluster.ingress.gateway.externalIP .Values.aiscluster.ingress.gateway.port }}
#
# LoadBalancer gateway service to expose AIS proxy service.
# The selector matches only electable proxies.
# External clients connect to port 51080 (port) and are forwarded
# to the same port number 51080 in the container (targetPort).
# MetalLB will allocate an IP in the range it controls;
# or we can specify one in that range - we choose the latter
# approach for initial simplicity.
#
# We use externalTrafficPolicy of "local" to preserve client IP addresses; this is
# used in AIS to distinguish external clients from those internal to its k8s cluster
# (necessary since we're running all of public/intra-control/intra-data on the same
# interface).
#
apiVersion: v1
kind: Service
metadata:
  name: {{  template "ais.fullname" . }}-gw
spec:
  ports:
  - name: http
    port: {{ .Values.aiscluster.ingress.gateway.port }}
    protocol: TCP
    targetPort: {{ .Values.aiscluster.ingress.gateway.targetPort }}
  selector:
    app: {{ template "ais.name" . }}
    release: {{ .Release.Name }}
    component: proxy
    function: gateway
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: {{ .Values.aiscluster.ingress.gateway.externalIP | quote }}
{{ end }}
---
{{ if and .Values.aiscluster.ingress.grafana.externalIP .Values.aiscluster.ingress.grafana.port }}
apiVersion: v1
kind: Service
metadata:
  name: {{  template "ais.fullname" . }}-grafana
spec:
  ports:
  - name: grafana
    port: {{ .Values.aiscluster.ingress.grafana.port }}
    protocol: TCP
    targetPort: {{ .Values.aiscluster.ingress.grafana.targetPort }}
  selector:
    app: grafana
    release: {{ .Release.Name }}
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: {{ .Values.aiscluster.ingress.grafana.externalIP | quote }}
{{ end }}