apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "ais.fullname" . }}-proxy
  labels:
    app: {{ template "ais.name" . }}
    chart: {{ template "ais.chart" . }}
    component: "{{ .Values.proxy.name }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.aiscluster.expected_proxy_nodes }}
  serviceName: {{ template "ais.fullname" . }}-proxy
  selector:
    matchLabels:
      app: "{{ template "ais.name" . }}"
      component: "{{ .Values.proxy.name }}"
      release: "{{ .Release.Name }}"
      function: "gateway"
  updateStrategy:
    type: RollingUpdate
  # Necessary - otherwise deployment would work only if the primary was the first proxy started.
  podManagementPolicy: "Parallel"
  template:
    metadata:
      labels:
        app: {{ template "ais.name" . }}
        component: "{{ .Values.proxy.name }}"
        release: {{ .Release.Name }}
        function: "gateway"
    spec:
      initContainers:
        - name: populate-env
          image: {{ .Values.aiscluster.image.kubectl.repository }}:{{ .Values.aiscluster.image.kubectl.tag }}
          imagePullPolicy: {{ .Values.aiscluster.image.pullPolicy }}
          env:
            - name: DEFAULT_PRIMARY_POD
              value: {{ template "ais.fullname" . }}-proxy-0
            - name: MY_NODE
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_SERVICE
              value: {{ template "ais.fullname" . }}-proxy
            - name: AIS_NODE_ROLE
              value: "proxy"
            - name: K8S_NS
              value: {{ .Release.Namespace }}
            - name: CLUSTERIP_PROXY_SERVICE_HOSTNAME
              value: {{ template "ais.fullname" . }}-proxy
            - name: CLUSTERIP_PROXY_SERVICE_PORT
              value: "{{ .Values.proxy.service.port }}"
          command:
            - "/bin/bash"
          args: [ "-c", "/bin/bash /var/ais_config_template/set_initial_primary_proxy_env.sh" ]
          volumeMounts:
            - name: config-template-mount
              mountPath: "/var/ais_config_template"
            - name: config-mount
              mountPath: "/var/ais_config"
            - name: env-mount
              mountPath: "/var/ais_env"

      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.aiscluster.image.aisnode.repository }}:{{ .Values.aiscluster.image.aisnode.tag }}"
          imagePullPolicy: {{ .Values.aiscluster.image.pullPolicy }}
          securityContext:
            capabilities:
              add:
                {{ range .Values.aiscluster.k8s.container_capabilities }}
                - {{ . }}
                {{ end }}
          env:
            - name: AIS_CONF_FILE
              value: "/var/ais_config/ais.json"
            - name: AIS_LOCAL_CONF_FILE
              value: "/var/ais_config/ais_local.json"
            - name: STATSD_CONF_FILE
              value: "/var/statsd_config/statsd.json"
            - name: AIS_NODE_ROLE
              value: "proxy"
            - name: AIS_HELM_DEPLOYMENT
              value: "true"
            - name: TARGETS
              value: {{ .Values.aiscluster.expected_target_nodes | quote }}
            {{ if not .Values.aiscluster.skipHostIP }}
            - name: AIS_HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            {{ end }}
            - name: AIS_CLUSTER_CIDR
              value: {{ .Values.aiscluster.k8s.cluster_cidr | quote }}
            - name: CLUSTERIP_PROXY_SERVICE_HOSTNAME
              value: {{ template "ais.fullname" . }}-proxy
            - name: CLUSTERIP_PROXY_SERVICE_PORT
              value: "{{ .Values.proxy.service.port }}"
          ports:
            - name: http
              containerPort: {{ .Values.proxy.service.port }}
              protocol: TCP
          volumeMounts:
            - name: config-mount
              mountPath: "/var/ais_config"
            - name: env-mount
              mountPath: "/var/ais_env"
            - name: state-mount
              mountPath: "/etc/ais"
            - name: statsd-config
              mountPath: "/var/statsd_config"
            {{ if ne .Values.aiscluster.awsSecretName "" }}
            - name: aws-creds
              mountPath: "/.aws"
            {{ end }}
          lifecycle:
            preStop:
              exec:
                command: [ "/bin/bash", "-c", "/usr/bin/pkill -SIGINT aisnode" ]
          livenessProbe:
            httpGet:
              path: /v1/health
              port: {{ .Values.proxy.service.port }}
            initialDelaySeconds: 90
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
              - /ais_readiness.sh
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 5
            successThreshold: 1
          resources:
{{ toYaml .Values.proxy.resources | indent 12 }}
      securityContext:
        sysctls:
        {{ if .Values.aiscluster.k8s.sysctls.somaxconn }}
        - name: net.core.somaxconn
          value: {{ .Values.aiscluster.k8s.sysctls.somaxconn | quote }}
        {{ end }}
        - name: net.ipv4.ip_local_port_range
          value: "10240 65535"
      serviceAccount: {{ template "ais.name" . }}-sa
      nodeSelector:
         {{ .Values.proxy.nodeSelector.key }}: {{ template "ais.fullname" . }}-electable
      volumes:
        - name: config-mount
          emptyDir: {}
        {{ if ne .Values.aiscluster.awsSecretName "" }}
        - name: aws-creds
          secret:
            secretName: "{{ .Values.aiscluster.awsSecretName }}"
        {{ end }}
        - name: config-template-mount
          configMap:
            name:  {{ template "ais.name" . }}-proxy
        - name: env-mount
          hostPath:
            path: "{{ .Values.aiscluster.hostpathPrefix }}/{{ .Release.Name }}/proxy_env"
        - name: state-mount
          hostPath:
            path: "{{ .Values.aiscluster.hostpathPrefix }}/{{ .Release.Name }}/proxy"
        - name: statsd-config
          configMap:
            name: {{ template "ais.name" . }}-statsd
    {{- with .Values.proxy.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      imagePullSecrets:
        {{- range .Values.aiscluster.image.pullSecretNames }}
        - name: {{ . }}
        {{- end }}
