{{ if and (ne .Values.proxy.service.type "")  (ne .Values.proxy.service.type  "ClusterIP") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "ais.fullname" . }}-proxy-external
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: {{ template "ais.name" . }}
    chart: {{ template "ais.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.proxy.service.type }}
  ports:
    - port: {{ .Values.proxy.service.port }}
      targetPort: {{ .Values.proxy.service.port }}
      protocol: TCP
      name: http
  selector:
      app: "{{ template "ais.name" . }}"
      release: "{{ .Release.Name }}"
      function: "gateway"
{{ end }}
