{{ if eq .Values.target.service.type  "LoadBalancer" }}
{{- $root := . -}}
{{ range $podIndex := until (int .Values.aiscluster.expected_target_nodes) -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "ais.fullname" $root }}-target-{{ $podIndex }}
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: {{ template "ais.name" $root }}
    chart: {{ template "ais.chart" $root }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
spec:
  type: {{ $root.Values.target.service.type }}
  ports:
    - port: {{ $root.Values.target.service.port }}
      targetPort: {{ $root.Values.target.service.port }}
      protocol: TCP
      name: http
  selector:
      statefulset.kubernetes.io/pod-name: {{ template "ais.fullname" $root }}-target-{{ $podIndex }}
{{ end }}
---
{{ end }}
