apiVersion: v1
kind: Service
metadata:
  name: {{ template "ais.fullname" . }}-target
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: {{ template "ais.name" . }}
    chart: {{ template "ais.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.target.service.port }}
      targetPort: {{ .Values.target.service.port }}
      protocol: TCP
      name: pub
    - port: {{ .Values.target.config.net.l4.port_intra_control }}
      targetPort: {{ .Values.target.config.net.l4.port_intra_control }}
      protocol: TCP
      name: intra
    - port: {{ .Values.target.config.net.l4.port_intra_data }}
      targetPort: {{ .Values.target.config.net.l4.port_intra_data }}
      protocol: TCP
      name: data

  selector:
      app: "{{ template "ais.name" . }}"
      release: "{{ .Release.Name }}"
      function: "storage"
