apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ais.name" . }}-target
data:
  ais.json: |-
    {
{{- include "common.config" . | indent 6 }},
{{ with .Values.target.config -}}
{{ include "common_net.config" . | indent 6 }},
{{- end }} "proxy": {
              "non_electable": false,
              "primary_url":  "http://{{ template "ais.fullname" . }}-proxy:{{ .Values.proxy.config.net.l4.port }}",
              "original_url":  "http://{{ template "ais.fullname" . }}-proxy:{{ .Values.proxy.config.net.l4.port }}",
              "discovery_url":  "http://{{ template "ais.fullname" . }}-proxy:{{ .Values.proxy.config.net.l4.port }}"
      }
    }
  set_initial_target_env.sh: |-
{{ include "target.set_initial_target_env" . | indent 4 }}
  ais_local.json: |-
    {
{{ with .Values.target.config -}}
{{- include "local.config" . | indent 6 }},
{{- end }}
{{ include "local_fs.config" . | indent 6 }}
    }
