apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: $PVC_NAME
  namespace: default
spec:
  resources:
    requests:
      storage: 50Gi
  storageClassName: ais
  volumeName: $PV_NAME
  accessModes:
    - ReadWriteOnce